<?php


namespace App\DataFixtures\Faker\Provider;

use Faker\Provider\Base as BaseProvider;

class BookNameProvider extends BaseProvider
{
    const BOOK_NAMES = [
        'XVI',
        'The Yellow Wallpaper and Other Stories',
        'Year of Wonders	Year of Wonders',
        'The Year of the Flood',
        'You Slay Me',
        'Yellow Crocus	Yellow Crocus',
        'The Year of Magical Thinking',
        'Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values',
        'The Zookeeper\'s Wife',
        'You Suck',
        'A Novel of Zelda Fitzgerald	Z',
        'The Xibalba Murders ',
        'Holic, Vol. 1 ',
        'Zeitoun',
        'The Years of Rice and Salt	The Years of Rice and Salt',
        'Yours Until Dawn',
        'You\'re Never Weird on the Internet ',
        'Z for Zachariah',
        'Xoe',
        'The Zombie Survival Guide: Complete Protection from the Living Dead',
        'Zorro	Zorro',
        'You Are Special',
        'You',
        'Xanadu	Xanadu',
        'The Yearling',
        'You Against Me',
        'Zorba the Greek',
        'You Are So Undead to Me',
        'Yes Please',
        'The Young Elites',
        'X',
        'Zoo City',
        'A Year Down Yonder',
        'Yurara',
        'The Yiddish Policemen\'s Union',
        'Yu Yu Hakusho',
        'Volume 1: Goodbye, Material World!',
        'You Can\'t Take it With You',
        'Yertle the Turtle and Other Stories',
        'Zac and Mia',
        'Zorro\'s Last Stand by Mark Shearman',
        'A Year Without Autumn',
        'Zlata\'s Diary: A Child\'s Life in Wartime Sarajevo',
        'Zombie Queen of Newbury High',
        'The Year We Disappeared: A Father - Daughter Memoir',
        'Zone One',
        'Zoya',
        'Zeroes',
        'The Zoo Story and Other Plays',
        'The Young Unicorns ',
        'Zelda',
        'Yentl the Yeshiva Boy',
        'The Zimmermann Telegram',
        'Xingu',
        'Xtabentum: A Novel of Yucatan',
        'A Year in Japan',
        'Zig*Zag, Volume 1',
        'Yeats Is Dead!: A Mystery by 15 Irish Writers',
        'Youth',
        'Zombie',
        'The Yellow House Mystery',
        'Zel',
        'Zoo',
        'XBestia',
        'Xerxes Invades Greece',
        'Zero History',
        'Zoo ',
        'X Isle',
        'X Out Of Wonderland',
        'Zona: A Book About a Film About a Journey to a Room',
        'XO',
        'X-It',
        'Yours to Keep',
        'X',
        'Young Törless',
        'Zipped',
        'The Yellow Birds',
        'Zen and the Art of Vampires',
        'Zen Buddhism: Selected Writings of D. T. Suzuki',
        'The Yonahlossee Riding Camp for Girls',
        'Zeroes	Zeroes',
        'You Have to Stop This',
        'You Can\'t Keep a Good Woman Down',
        'A Year in the Life of William Shakespeare',
        'Yarrow',
        'Yaqui Delgado Wants to Kick Your Ass',
        'Your Mother Was a Neanderthal',
        'The Zoya Factor',
        'Zorgamazoo',
        'Zazen',
        'You Can\'t Read This Book: Censorship in an Age of Freedom',
        'You Come Too: Favorite Poems for Readers of All Ages',
        'The Zahir',
        'Yamamoto Zenjirou to Moushimasu, Vol. 01',
        'Yukon Ho!',
        'The Year of Reading Dangerously: How Fifty Great Books',
        'Zombies Vs. Unicorns',
        'Year One (Chronicles of The One, #1)',
        'You Know You Love Me ',
        'The Yummy Mummy',
    ];

    /**
     * @return string Random book names.
     */
    public function bookNames()
    {
        return self::randomElement(static::BOOK_NAMES);
    }
}