<?php

namespace App\DataFixtures\Faker\Provider\fr_FR;

use App\DataFixtures\Faker\Provider\BookNameProvider as BaseProvider;

class BookNameProvider extends BaseProvider
{
    const BOOK_NAMES = [
        'XVI',
        'Le papier peint jaune et autres histoires',
        'Année des Merveilles Année des Merveilles',
        'L\'année du déluge',
        'Tu me tues',
        'Crocus Jaune Crocus Jaune',
        "L'année de la pensée magique",
        "Zen et l'art de l'entretien des motos: une enquête sur les valeurs",
        'La femme du gardien de zoo',
        'Tu crains',
        'Un roman de Zelda Fitzgerald Z',
        'Les meurtres de Xibalba',
        'Holic, Vol. 1 ',
        'Zeitoun',
        'Les années du riz et du sel Les années du riz et du sel',
        'À toi jusqu\'à l\'aube',
        'Vous n\'êtes jamais bizarre sur Internet',
        'Z pour Zachariah',
        'Xoe',
        "Le guide de survie Zombie: Protection complète contre les morts-vivants",
        'Zorro Zorro',
        'Vous êtes spécial',
        'Vous',
        'Xanadu Xanadu',
        "Le Yearling",
        'Vous contre moi',
        'Zorba le Grec',
        'Tu es tellement mort-vivant pour moi',
        'Oui s\'il vous plaît',
        "Les jeunes élites",
        'X',
        "Zoo City",
        "Un an là-bas",
        'Yurara',
        'Union des policiers yiddish',
        'Yu Yu Hakusho',
        "Volume 1: Au revoir, monde matériel!",
        "Vous ne pouvez pas le prendre avec vous",
        'Yertle la tortue et autres histoires',
        'Zac et Mia',
        "Le dernier combat de Zorro par Mark Shearman",
        "Une année sans automne",
        'Le journal de Zlata: la vie d’un enfant en temps de guerre à Sarajevo',
        'Zombie Queen of Newbury High',
        'L\'année de la disparition: Un mémoire père-fille',
        "Zone One",
        'Zoya',
        "Zéros",
        'L\'histoire du zoo et autres jeux',
        "Les jeunes licornes",
        'Zelda',
        'Yentl le garçon Yeshiva',
        "Le télégramme Zimmermann",
        'Xingu',
        'Xtabentum: un roman du Yucatan',
        'Un an au Japon',
        'Zig * Zag, volume 1',
        'Yeats Is Dead !: Un mystère de 15 écrivains irlandais',
        'Jeunesse',
        'Zombi',
        'Le mystère de la maison jaune',
        'Zel',
        'Zoo',
        'XBestia',
        "Xerxès envahit la Grèce",
        "Histoire zéro",
        'Zoo ',
        'X Isle',
        'X Out Of Wonderland',
        "Zona: Un livre sur un film sur le voyage dans une pièce",
        'XO',
        'X-It',
        'À vous de garder',
        'X',
        'Jeune Törless',
        'Zippé',
        'Les oiseaux jaunes',
        "Zen et l'art des vampires",
        'Buddhism Zen: Écrits choisis de D. T. Suzuki',
        'Le camp d\'équitation pour filles de Yonahlossee',
        'Zéros Zéros',
        'Vous devez arrêter ça',
        "Vous ne pouvez pas empêcher une bonne femme",
        "Un an dans la vie de William Shakespeare",
        'Achillée',
        "Yaqui Delgado veut te botter le cul",
        'Ta mère était un Néandertalien',
        'Le facteur Zoya',
        'Zorgamazoo',
        'Zazen',
        "Vous ne pouvez pas lire ce livre: La censure à l’ère de la liberté",
        "Vous venez aussi: poèmes préférés des lecteurs de tous âges",
        'Le Zahir',
        'Yamamoto Zenjirou à Moushimasu, Vol. 01 ',
        'Yukon Ho!',
        "L'année de la lecture dangereusement: Comment cinquante grands livres",
        'Zombies Vs. Licornes ',
        'Tu sais que tu m\'aimes ',
        'La Maman Miam'
    ];
}